# Redis configuration file
# This file is intentionally kept basic to stop the "no config file specified" warning.

# Set log level
loglevel notice

# Disable saving to disk (since this is currently used mostly as a message broker for Celery)
save ""
appendonly no
