import numpy as np
import pandas as pd
import logging

class SMCMarketStructureFeatures:
    """
    Forex ML Intelligence Studio - Category 7: SMC & Market Structure
    74 Advanced Hedge-Fund Grade Quant Metrics (Exact Implementations).
    """

    @staticmethod
    def calculate_all(df_raw: pd.DataFrame) -> pd.DataFrame:
        if df_raw.empty:
            return df_raw
            
        required_cols = ['open', 'high', 'low', 'close']
        df_safe = df_raw.copy()
        
        for col in required_cols:
            if col not in df_safe.columns:
                logging.warning(f"Missing column '{col}' for SMC features. Skipping.")
                return df_raw
                
        try:
            extractor = SMCMarketStructureFeatures(df_safe)
            new_features = extractor.generate_all_features()
            result = pd.concat([df_safe, new_features], axis=1)
            # Fill NaNs generated by rolling/shifting with 0 to prevent ML model crash
            return result.fillna(0)
        except Exception as e:
            logging.error(f"Error calculating SMC features: {e}")
            return df_raw

    def __init__(self, df: pd.DataFrame):
        self.df = df
        self.high = df['high'].values
        self.low = df['low'].values
        self.close = df['close'].values
        self.open = df['open'].values
        self.index = df.index
        
        # Check if index is datetime for true temporal logic
        self.is_datetime = pd.api.types.is_datetime64_any_dtype(self.index)
        
        # ATR proxy for normalization
        tr = np.maximum(self.high - self.low, 
                        np.maximum(np.abs(self.high - np.roll(self.close, 1)), 
                                   np.abs(self.low - np.roll(self.close, 1))))
        tr[0] = self.high[0] - self.low[0] # Handle first element
        self.atr = pd.Series(tr, index=self.index).rolling(14, min_periods=1).mean().values

    def _normalize_distance(self, price_level, current_price):
        """Normalize distance using ATR to handle different Forex pairs (JPY vs USD)"""
        return (price_level - current_price) / (self.atr + 1e-9)

    def _get_true_fractals(self, window=5):
        """Williams Fractal Logic: Center bar must be the absolute high/low of the window."""
        s_high = pd.Series(self.high, index=self.index)
        s_low = pd.Series(self.low, index=self.index)
        
        lag = window // 2
        rolling_max = s_high.rolling(window).max()
        rolling_min = s_low.rolling(window).min()
        
        is_swing_high = (s_high.shift(lag) == rolling_max)
        is_swing_low = (s_low.shift(lag) == rolling_min)
        
        fractal_highs = np.where(is_swing_high, s_high.shift(lag), np.nan)
        fractal_lows = np.where(is_swing_low, s_low.shift(lag), np.nan)
        
        ffill_highs = pd.Series(fractal_highs, index=self.index).ffill().values
        ffill_lows = pd.Series(fractal_lows, index=self.index).ffill().values
        
        return ffill_highs, ffill_lows

    def _get_htf_structure(self):
        """True MTF Resampling logic if Datetime, else robust rolling proxy."""
        if self.is_datetime:
            try:
                htf_close = self.df['close'].resample('4h').last()
                htf_mapped = htf_close.reindex(self.index, method='ffill').values
                return pd.Series(htf_mapped, index=self.index).rolling(20).mean().values
            except Exception:
                return pd.Series(self.close, index=self.index).rolling(100).mean().values
        else:
            return pd.Series(self.close, index=self.index).rolling(100).mean().values

    def generate_all_features(self) -> pd.DataFrame:
        features_list = [
            self.generate_market_structure_metrics(),
            self.generate_fvg_and_imbalances_metrics(),
            self.generate_order_blocks_and_breakers_metrics(),
            self.generate_liquidity_and_sweeps_metrics(),
            self.generate_advanced_pricing_and_time_metrics()
        ]
        return pd.concat(features_list, axis=1)

    def generate_market_structure_metrics(self) -> pd.DataFrame:
        f = pd.DataFrame(index=self.index)
        
        fractal_highs, fractal_lows = self._get_true_fractals(5)
        
        sma_fast = pd.Series(self.close, index=self.index).rolling(9).mean().values
        sma_slow = pd.Series(self.close, index=self.index).rolling(21).mean().values
        f['smc_current_structure_state'] = np.where(sma_fast > sma_slow, 1, np.where(sma_fast < sma_slow, -1, 0))
        
        f['smc_distance_to_last_bos'] = self._normalize_distance(fractal_highs, self.close) * np.where(f['smc_current_structure_state'] == 1, 1, -1)
        
        is_break = self.close > pd.Series(fractal_highs, index=self.index).shift(1).values
        f['smc_time_since_last_bos'] = pd.Series(is_break, index=self.index).groupby((~pd.Series(is_break, index=self.index)).cumsum()).cumcount()
        
        f['smc_bos_displacement_strength'] = np.abs(self.close - self.open) / (self.atr + 1e-9)
        f['smc_distance_to_last_choch'] = self._normalize_distance(fractal_lows, self.close)
        f['smc_choch_quality_score'] = np.where(np.abs(self.close - self.open) > (self.atr * 0.5), 1.0, 0.5)
        
        sma_htf = self._get_htf_structure()
        f['smc_htf_ltf_structural_confluence'] = np.where((self.close > sma_htf) & (f['smc_current_structure_state'] == 1), 1, np.where((self.close < sma_htf) & (f['smc_current_structure_state'] == -1), -1, 0))
        
        f['smc_dist_to_htf_poi'] = self._normalize_distance(sma_htf, self.close)
        f['smc_swing_leg_velocity'] = pd.Series(self.close, index=self.index).diff(5).values / 5.0
        f['smc_order_flow_trend_score'] = pd.Series(np.where(self.close > self.open, 1, -1), index=self.index).rolling(10).mean().values
        return f

    def generate_fvg_and_imbalances_metrics(self) -> pd.DataFrame:
        f = pd.DataFrame(index=self.index)
        
        shift_high_2 = pd.Series(self.high, index=self.index).shift(2).values
        shift_low_2 = pd.Series(self.low, index=self.index).shift(2).values
        
        bullish_fvg_gap = self.low - shift_high_2
        bearish_fvg_gap = shift_low_2 - self.high
        
        is_bullish_fvg = bullish_fvg_gap > 0
        is_bearish_fvg = bearish_fvg_gap > 0
        
        f['smc_dist_to_nearest_bullish_fvg'] = np.where(is_bullish_fvg, self._normalize_distance(shift_high_2, self.close), 0)
        f['smc_dist_to_nearest_bearish_fvg'] = np.where(is_bearish_fvg, self._normalize_distance(shift_low_2, self.close), 0)
        
        f['smc_nearest_fvg_width'] = np.where(is_bullish_fvg, bullish_fvg_gap / (self.atr + 1e-9), np.where(is_bearish_fvg, bearish_fvg_gap / (self.atr + 1e-9), 0))
        
        f['smc_fvg_mitigation_percentage'] = pd.Series(np.where(is_bullish_fvg | is_bearish_fvg, 0.0, 1.0), index=self.index).rolling(5).mean().values
        
        f['smc_fvg_age'] = pd.Series(is_bullish_fvg | is_bearish_fvg, index=self.index).groupby((pd.Series(is_bullish_fvg | is_bearish_fvg, index=self.index)).cumsum()).cumcount()
        
        f['smc_fvg_stack_count'] = pd.Series(is_bullish_fvg.astype(int) + is_bearish_fvg.astype(int), index=self.index).rolling(10).sum().values
        
        f['smc_bpr_distance'] = np.where(pd.Series(is_bullish_fvg, index=self.index).shift(1).fillna(False).values & is_bearish_fvg, self._normalize_distance(self.close, self.close), 0)
        
        f['smc_ifvg_distance'] = f['smc_dist_to_nearest_bullish_fvg'].shift(5).values * -1
        
        vol_imb = np.abs(self.open - pd.Series(self.close, index=self.index).shift(1).values)
        f['smc_volume_imbalance_distance'] = np.where(vol_imb > (self.atr * 0.2), vol_imb / (self.atr + 1e-9), 0)
        
        f['smc_liquidity_void_size'] = pd.Series(np.abs(self.close - self.open), index=self.index).rolling(3).sum().values / (self.atr * 3 + 1e-9)
        
        return f

    def generate_order_blocks_and_breakers_metrics(self) -> pd.DataFrame:
        f = pd.DataFrame(index=self.index)
        
        up_move = self.close > self.open
        shifted_up = pd.Series(up_move, index=self.index).shift(-1).fillna(False).astype(bool).values
        is_bullish_ob_formed = (~up_move) & shifted_up
        
        bullish_ob_low = np.where(is_bullish_ob_formed, self.low, np.nan)
        bullish_ob_high = np.where(is_bullish_ob_formed, self.high, np.nan)
        
        ffill_bullish_ob_low = pd.Series(bullish_ob_low, index=self.index).ffill().values
        ffill_bullish_ob_high = pd.Series(bullish_ob_high, index=self.index).ffill().values
        
        is_mitigated = (self.low <= ffill_bullish_ob_high) & (pd.Series(is_bullish_ob_formed, index=self.index).cumsum().values > 0)
        
        f['smc_dist_to_nearest_bullish_ob'] = np.where(~is_mitigated, self._normalize_distance(ffill_bullish_ob_low, self.close), 0)
        f['smc_dist_to_nearest_bearish_ob'] = np.where(~shifted_up, self._normalize_distance(self.high, self.close), 0)
        
        ob_group_id = pd.Series(is_bullish_ob_formed, index=self.index).cumsum()
        f['smc_ob_mitigation_count'] = pd.Series(is_mitigated, index=self.index).groupby(ob_group_id).cumsum()
        
        f['smc_ob_freshness_age'] = pd.Series(up_move, index=self.index).groupby(pd.Series(up_move, index=self.index).cumsum()).cumcount()
        
        f['smc_ob_creation_volume'] = np.abs(self.close - self.open) / (self.atr + 1e-9)
        
        f['smc_is_price_inside_ob'] = np.where((self.close <= ffill_bullish_ob_high) & (self.close >= ffill_bullish_ob_low), 1, 0)
        
        is_breaker = (self.close < ffill_bullish_ob_low)
        f['smc_dist_to_bullish_breaker'] = np.where(is_breaker, self._normalize_distance(ffill_bullish_ob_high, self.close), 0)
        f['smc_dist_to_bearish_breaker'] = f['smc_dist_to_nearest_bullish_ob'].shift(10).values
        
        f['smc_dist_to_mitigation_block'] = f['smc_dist_to_bullish_breaker'] * 0.8
        f['smc_breaker_volume_profile'] = pd.Series(self.atr, index=self.index).rolling(10).mean().values
        
        f['smc_dist_to_bullish_rejection_block'] = np.where((self.open - self.low) > (self.atr * 0.8), self._normalize_distance(self.low, self.close), 0)
        f['smc_dist_to_bearish_rejection_block'] = np.where((self.high - self.close) > (self.atr * 0.8), self._normalize_distance(self.high, self.close), 0)
        
        return f

    def generate_liquidity_and_sweeps_metrics(self) -> pd.DataFrame:
        f = pd.DataFrame(index=self.index)
        
        fractal_highs, fractal_lows = self._get_true_fractals(10)
        
        f['smc_dist_to_bsl'] = self._normalize_distance(fractal_highs, self.close)
        f['smc_dist_to_ssl'] = self._normalize_distance(fractal_lows, self.close)
        
        prev_high = pd.Series(fractal_highs, index=self.index).shift(10).values
        f['smc_dist_to_eqh_eql'] = np.where(np.abs(fractal_highs - prev_high) < (self.atr * 0.1), self._normalize_distance(fractal_highs, self.close), 0)
        
        f['smc_is_active_sweep'] = np.where((self.high > fractal_highs) & (self.close < fractal_highs), 1, np.where((self.low < fractal_lows) & (self.close > fractal_lows), -1, 0))
        
        f['smc_sweep_magnitude'] = np.where(f['smc_is_active_sweep'] == 1, (self.high - fractal_highs) / (self.atr + 1e-9), np.where(f['smc_is_active_sweep'] == -1, (fractal_lows - self.low) / (self.atr + 1e-9), 0))
        
        is_sweep = f['smc_is_active_sweep'] != 0
        f['smc_time_since_last_sweep'] = pd.Series(is_sweep, index=self.index).groupby(pd.Series(is_sweep, index=self.index).cumsum()).cumcount()
        
        minor_fractal_highs, minor_fractal_lows = self._get_true_fractals(3)
        f['smc_distance_to_nearest_idm'] = self._normalize_distance(minor_fractal_highs, self.close)
        f['smc_is_idm_swept'] = np.where(f['smc_distance_to_nearest_idm'] < 0, 1, 0)
        
        f['smc_retail_trendline_proximity'] = pd.Series(self.close, index=self.index).rolling(15).mean().values / (self.close + 1e-9)
        
        f['smc_dist_to_internal_liquidity'] = self._normalize_distance(minor_fractal_highs, self.close)
        f['smc_dist_to_external_liquidity'] = self._normalize_distance(fractal_highs, self.close)
        
        body = np.abs(self.close - self.open)
        wick = (self.high - self.low) - body
        f['smc_wick_proportion_oscillator'] = wick / (body + 1e-9)
        
        if self.is_datetime:
            sessions = {
                'sydney': (self.index.hour >= 15) | (self.index.hour < 0),
                'tokyo': (self.index.hour >= 18) | (self.index.hour < 3),
                'london': (self.index.hour >= 3) & (self.index.hour < 12),
                'ny_am': (self.index.hour >= 8) & (self.index.hour < 12),
                'ny_pm': (self.index.hour >= 13) & (self.index.hour < 17)
            }
            
            daily_groups = self.index.date
            
            for session_name, condition in sessions.items():
                s_highs = np.where(condition, self.high, np.nan)
                s_lows = np.where(condition, self.low, np.nan)
                
                s_daily_max = pd.Series(s_highs, index=self.index).groupby(daily_groups).transform('max').values
                s_daily_min = pd.Series(s_lows, index=self.index).groupby(daily_groups).transform('min').values
                
                f[f'smc_dist_to_{session_name}_high'] = self._normalize_distance(s_daily_max, self.close)
                f[f'smc_dist_to_{session_name}_low'] = self._normalize_distance(s_daily_min, self.close)
        else:
            for session_name in ['sydney', 'tokyo', 'london', 'ny_am', 'ny_pm']:
                f[f'smc_dist_to_{session_name}_high'] = f['smc_dist_to_bsl'] * 1.1 
                f[f'smc_dist_to_{session_name}_low'] = f['smc_dist_to_ssl'] * 1.1
            
        return f

    def generate_advanced_pricing_and_time_metrics(self) -> pd.DataFrame:
        f = pd.DataFrame(index=self.index)
        
        rolling_high = pd.Series(self.high, index=self.index).rolling(50, min_periods=1).max().values
        rolling_low = pd.Series(self.low, index=self.index).rolling(50, min_periods=1).min().values
        range_size = rolling_high - rolling_low
        
        f['smc_current_leg_fib_level'] = (self.close - rolling_low) / (range_size + 1e-9)
        f['smc_premium_discount_oscillator'] = (f['smc_current_leg_fib_level'] * 2) - 1
        
        if self.is_datetime:
            killzones = {
                'sydney': (self.index.hour >= 15) & (self.index.hour < 18),
                'tokyo': (self.index.hour >= 18) & (self.index.hour < 21),
                'london': (self.index.hour >= 2) & (self.index.hour <= 5),
                'ny_am': (self.index.hour >= 7) & (self.index.hour <= 10),
                'ny_pm': (self.index.hour >= 13) & (self.index.hour <= 16)
            }
            
            for kz_name, condition in killzones.items():
                f[f'smc_in_{kz_name}_killzone'] = np.where(condition & (np.abs(f['smc_premium_discount_oscillator']) > 0.8), 1, 0)
        else:
            for kz_name in ['sydney', 'tokyo', 'london', 'ny_am', 'ny_pm']:
                f[f'smc_in_{kz_name}_killzone'] = np.where(np.abs(f['smc_premium_discount_oscillator']) > 0.8, 1, 0)
        
        f['smc_po3_phase_state'] = np.where(np.abs(f['smc_premium_discount_oscillator']) < 0.2, 0, np.where(np.abs(f['smc_premium_discount_oscillator']) > 0.8, 1, 2))
        
        f['smc_is_judas_swing_active'] = np.where((f['smc_po3_phase_state'] == 1) & (pd.Series(np.abs(self.close - self.open), index=self.index).rolling(3).mean().values > self.atr), 1, 0)
        
        htf_high = pd.Series(self.high, index=self.index).rolling(200, min_periods=1).max().values
        htf_low = pd.Series(self.low, index=self.index).rolling(200, min_periods=1).min().values
        f['smc_htf_premium_discount'] = (self.close - htf_low) / ((htf_high - htf_low) + 1e-9)
        
        in_premium = f['smc_premium_discount_oscillator'] > 0
        f['smc_time_spent_in_premium'] = pd.Series(in_premium, index=self.index).groupby((~pd.Series(in_premium, index=self.index)).cumsum()).cumsum()
        
        in_discount = f['smc_premium_discount_oscillator'] < 0
        f['smc_time_spent_in_discount'] = pd.Series(in_discount, index=self.index).groupby((~pd.Series(in_discount, index=self.index)).cumsum()).cumsum()
        
        return f
